# Generated by Django 3.1.2 on 2020-12-01 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('firstname', models.CharField(default=None, max_length=60)),
                ('lastname', models.CharField(default=None, max_length=60, null=True)),
                ('othernames', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('phone_num', models.CharField(max_length=60, unique=True)),
                ('profiles', models.CharField(default=None, max_length=700, null=True)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.IntegerField(default=None, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('dependent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'All User',
            },
        ),
    ]
